DROP TABLE IF EXISTS "City";
CREATE TABLE City (_id INTEGER PRIMARY KEY, Name TEXT);
DROP TABLE IF EXISTS "Regions";
CREATE TABLE Regions (_id INTEGER PRIMARY KEY, Name TEXT);
DROP TABLE IF EXISTS "Status";
CREATE TABLE Status (_id INTEGER PRIMARY KEY, name TEXT);
DROP TABLE IF EXISTS "Streets";
CREATE TABLE Streets (_id INTEGER PRIMARY KEY, Name TEXT);
DROP TABLE IF EXISTS "Tasks";
CREATE TABLE Tasks (_id INTEGER PRIMARY KEY, user TEXT, task TEXT);
DROP TABLE IF EXISTS "Types";
CREATE TABLE "Types" ("_id" INTEGER PRIMARY KEY  NOT NULL , "Name" TEXT);
DROP TABLE IF EXISTS "access";
CREATE TABLE access (_id INTEGER PRIMARY KEY);
DROP TABLE IF EXISTS "android_metadata";
CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'ru_RU');
INSERT INTO "android_metadata" VALUES('en_EN');
DROP TABLE IF EXISTS "data";
CREATE TABLE data (phone TEXT, _id INTEGER PRIMARY KEY, type TEXT, city TEXT, region TEXT, street TEXT, home TEXT, room TEXT, floor TEXT, storey TEXT, material TEXT, gross_area TEXT, living_space TEXT, kitchen_area TEXT, cost INTEGER, comment TEXT, "Status" TEXT);
DROP TABLE IF EXISTS "system";
CREATE TABLE system (version TEXT);
