BEGIN TRANSACTION;
CREATE TABLE City (_id INTEGER PRIMARY KEY, Name TEXT);
CREATE TABLE Regions (_id INTEGER PRIMARY KEY, Name TEXT);
CREATE TABLE Streets (_id INTEGER PRIMARY KEY, Name TEXT);
CREATE TABLE Types (_id TEXT, Name TEXT);
CREATE TABLE access (id INTEGER PRIMARY KEY);
CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'ru_RU');
INSERT INTO android_metadata VALUES('ru_RU');
CREATE TABLE data (_id INTEGER PRIMARY KEY, type TEXT, city TEXT, region TEXT, street TEXT, home TEXT, room TEXT, floor TEXT, storey TEXT, material TEXT, gross_area TEXT, living_space TEXT, kitchen_area TEXT, cost TEXT, comment TEXT);
CREATE TABLE system (version TEXT);
COMMIT;
